name: "Update Bot"

permissions:
  contents: write
  actions: write
  pull-requests: write

on:
  schedule:
    - cron: '0 */5 * * *'
  push:
    branches:
      - master
      - main

      
jobs:
  update-data:
    name: Update Bot
    runs-on: "macos-latest"
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - name: Setup - Checkout repo
        uses: actions/checkout@v2
      - name: "Setup - Install Packages"
        run: |
          install.packages('remotes')
          remotes::install_github('favstats/discordr')
          install.packages('httr')
        shell: Rscript {0}
      - name: "Check for updates"
        run: Rscript 'bot_update.R'
        env:
          r_discord_bot_django: ${{ secrets.R_DISCORD_BOT_DJANGO }}
          gpt3: ${{ secrets.GPT3 }}
      - name: "Commit"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Routine Update
